services:
  - type: web
    name: fixate
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
