DROP TABLE `chat_rooms`;--> statement-breakpoint
DROP TABLE `coupon_usage`;--> statement-breakpoint
DROP TABLE `coupons`;--> statement-breakpoint
DROP TABLE `device_models`;--> statement-breakpoint
DROP TABLE `device_types`;--> statement-breakpoint
DROP TABLE `loyalty_points`;--> statement-breakpoint
DROP TABLE `messages`;--> statement-breakpoint
DROP TABLE `payment_receipts`;--> statement-breakpoint
DROP TABLE `points_transactions`;--> statement-breakpoint
DROP TABLE `push_subscriptions`;--> statement-breakpoint
DROP TABLE `reviews`;--> statement-breakpoint
DROP TABLE `rewards`;--> statement-breakpoint
DROP TABLE `service_pricing`;--> statement-breakpoint
DROP TABLE `service_requests`;--> statement-breakpoint
DROP TABLE `service_types`;--> statement-breakpoint
DROP TABLE `technician_locations`;--> statement-breakpoint
DROP TABLE `technician_profiles`;--> statement-breakpoint
DROP TABLE `technicians`;--> statement-breakpoint
DROP TABLE `users`;